[package]
name = "gotime"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = { version = "0.64.0", default-features = false }

[dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
