//! Imports and exports to the Gotime runtime.

/// Generated automatically by `bindgen` from the header generated by the Go compiler.
pub mod generated {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]

    include!(concat!(env!("OUT_DIR"), "/runtime.rs"));
}

#[no_mangle]
pub extern "C" fn rust_hello_world() {
    println!("Hello from Rust lib")
}
